import Link from "next/link"
import "../globals.css"
import { getPages } from "@/sanity/sanity-utils"

export const metadata = {
  title: "My Next/Sanity Experiment",
  description:
    "My test project generated by create next app with data hosted on Sanity",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // fetch the reference to our pages here
  const pages = await getPages()

  return (
    <html lang='en'>
      <body className='bg-blue-300 max-w-3xl mx-auto py-10'>
        <header className='flex items-center justify-between'>
          <Link href='/' className='text-lg text-blue-800 font-bold'>
            Home
          </Link>
          <div className='flex items-center gap-5 text-blue-900'>
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className='hover:underline'
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
